#!/usr/bin/with-contenv sh

INIT_DIR=${DEF_CONFIG}/custom/init.d
SERVICE_DIR=${DEF_CONFIG}/custom/service.d

init(){
	echo "[custom-init] executing: ${2}"
	/bin/sh ${1}
}

service(){
	echo "[custom-service] installing ... ${2}"
	CUSTOM_DIR=/etc/services.d/custom-${2}
	mkdir -p ${CUSTOM_DIR}
	cp ${1} ${CUSTOM_DIR}/run
	chmod +x ${CUSTOM_DIR}/run
}

install_scripts(){
	if [[ -d ${1} ]]; then
		res=$(ls -A $1 2>/dev/null)
	  if [[ ! -z ${res} ]]; then
	    for SCRIPT in ${1}/*
	      do
					NAME="$(basename ${SCRIPT})"
					if [[ -f ${SCRIPT} ]]; then
						${2} ${SCRIPT} ${NAME}
					else
						echo "[custom-$2] not a valid $2 file"
					fi
	      done
	  fi
	else
		mkdir -p ${1}
		chown -R ${DEF_USER}:${DEF_USER} ${DEF_CONFIG}
	fi
}

install_scripts ${INIT_DIR} init
install_scripts ${SERVICE_DIR} service

